# before running docker-compose up for the first time,
# either do a pull:
# docker-compose pull
# or do a build:
# GIT_HASH $(git rev-parse --short HEAD) docker-compose up --detach

# subsequently you should only need to run:
# docker-compose up --detach

# force a full re-build with no cache from previous builds:
# docker-compose build --build-arg GIT_HASH $(git rev-parse --short HEAD) --parallel --no-cache

# to stop:
# docker-compose down

version: "3.4"

services:
  server:
    container_name: polis-server
    image: ghcr.io/demdis/polis-server:${VERSION}
    env_file: ./server/docker-dev.env
    restart: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
      - "file-server"
    networks:
      - "polis-net"
    ports:
      - "5001:5001"

  math:
    container_name: polis-math
    image: ghcr.io/demdis/polis-math:${VERSION}
    env_file: ./math/docker-dev.env
    restart: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - "postgres"
    build:
      context: ./math
    networks:
      - "polis-net"

  postgres:
    container_name: polis-postgres
    image: ghcr.io/demdis/polis-db:${VERSION}
    restart: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile-db
    networks:
      - "polis-net"
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    volumes:
      - "backups:/backups"
      - "postgres:/var/lib/postgresql/data"

  caddy:
    container_name: polis-caddy
    image: caddy:2-alpine
    environment:
      PRIMARY_POLIS_URL: ${PRIMARY_POLIS_URL}
    restart: on-failure
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - certificates:/data/caddy
    depends_on:
      - "server"
    networks:
      - "polis-net"
    ports:
      - "80:80"
      - "443:443"

  file-server:
    container_name: polis-file-server
    image: ghcr.io/demdis/polis-file-server:${VERSION}
    env_file: ./.env
    restart: on-failure
    build:
      context: ./
      dockerfile: file-server/Dockerfile
      args:
        GIT_HASH: "${GIT_HASH}"
    networks:
      - "polis-net"
    ports:
      - "8080:8080"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: on-failure
    ports:
      - "9200:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: on-failure
    command:
      - '--path.rootfs=/host'
    pid: host
    network_mode: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

networks:
  polis-net:

volumes:
  backups:
  postgres:
  certificates:
